// Downloads the web fonts used by the site into public/assets/fonts/ so no third-party CDN is needed at runtime.
// Both fonts are SIL Open Font License 1.1. Run once (or when upgrading a font): node scripts/fetch-fonts.mjs
import { mkdir, rm, writeFile } from 'node:fs/promises';

const OUT = new URL('../public/assets/fonts/', import.meta.url);
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';

const SOURCES = [
  { name: 'jua', css: 'https://fonts.googleapis.com/css2?family=Jua&display=swap', license: 'https://raw.githubusercontent.com/google/fonts/main/ofl/jua/OFL.txt' },
  { name: 'pretendard', css: 'https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css', license: 'https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/LICENSE' },
];

async function get(url, as = 'text') {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return as === 'text' ? res.text() : Buffer.from(await res.arrayBuffer());
}

async function pool(tasks, size = 12) {
  const queue = [...tasks];
  await Promise.all(Array.from({ length: size }, async () => { while (queue.length) await queue.shift()(); }));
}

await rm(OUT, { recursive: true, force: true });
let combined = '/* Self-hosted web fonts (SIL OFL 1.1). Generated by scripts/fetch-fonts.mjs — do not edit. */\n';
let files = 0;

for (const src of SOURCES) {
  const dir = new URL(`${src.name}/`, OUT);
  await mkdir(dir, { recursive: true });
  let css = await get(src.css);
  const urls = [...new Set([...css.matchAll(/url\(([^)]+)\)/g)].map((m) => m[1].replace(/['"]/g, '')))];
  const tasks = urls.map((u, i) => async () => {
    const abs = new URL(u, src.css).href;
    const file = `${String(i).padStart(3, '0')}.woff2`;
    await writeFile(new URL(file, dir), await get(abs, 'buffer'));
    css = css.split(u).join(`${src.name}/${file}`);
    files++;
  });
  await pool(tasks);
  combined += `\n/* ${src.name} */\n${css.replace(/\/\*[\s\S]*?\*\//g, '').trim()}\n`;
  await writeFile(new URL('LICENSE.txt', dir), await get(src.license));
}

await writeFile(new URL('fonts.css', OUT), combined);
console.log(`✓ ${files} font files → public/assets/fonts/ (fonts.css)`);
